Abc2.Northwind.MvcWebUi/Controllers/CartController.cs
using Abc2.Northwind.Business.Abstract;
using Abc2.Northwind.Entitites.Concrete;
using Abc2.Northwind.MvcWebUi.Models;
using Abc2.Northwind.MvcWebUi.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Abc2.Northwind.MvcWebUi.Controllers
{
    public class CartController : Controller
    {

        private ICartSessionService _cartSessionService;
        private ICartService _cartService;
        private IProductService _productService;

        public CartController(ICartSessionService cartSessionService,ICartService cartService,IProductService productService)
        {
            _cartSessionService = cartSessionService;
            _cartService = cartService;
            _productService = productService;
        }

        public IActionResult AddToCart(int productId)
        {
            var product = _productService.GetById(productId);
            var cart = _cartSessionService.GetCart();
            _cartService.AddToCart(cart, product);
            _cartSessionService.SetCart(cart);

            TempData["message"] = String.Format("Your product, {0} , was successfully added to the cart!",product.ProductName);

            return RedirectToAction("Index", "Product");
        }

        public IActionResult CartList()
        {
            var cart = _cartSessionService.GetCart();

            var model = new CartSummaryViewModel()
            {
                Cart = cart
            };

            return View(model);
        }

        public IActionResult Remove(int productId)
        {
            var cart = _cartSessionService.GetCart();
            _cartService.RemoveFromCart(cart, productId);
            _cartSessionService.SetCart(cart);
            return RedirectToAction("CartList");
        }

        [HttpGet]
        public IActionResult Complete()
        {
            var model = new ShippingDetailsViewModel()
            {
                ShippingDetails = new ShippingDetails()
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Complete(ShippingDetails shippingDetails)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            TempData["message"] = String.Format("Thank you {0}, your order is in process", shippingDetails.FirstName);
            return View();
        }
    }
}

Abc2.Northwind.MvcWebUi/Controllers/ProductController.cs
using Abc2.Northwind.Business.Abstract;
using Abc2.Northwind.MvcWebUi.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Abc2.Northwind.MvcWebUi.Controllers
{
    public class ProductController : Controller
    {

        private IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Index(int page = 1,int categoryId = 0)
        {
            int pageSize = 10;
            var products = _productService.GetByCategoryId(categoryId);
            ProductListViewModel model = new ProductListViewModel
            {
                Products = products.Skip((page - 1) * pageSize).Take(pageSize).ToList(),
                PageCount = (int)Math.Ceiling(products.Count/(double)pageSize),
                PageSize = pageSize,
                CurrentPage = page,
                CurrentCategoryId = categoryId
            };
            return View(model);
        }
    }
}

Abc2.Northwind.MvcWebUi/Views/Product/Index.cshtml
@model Abc2.Northwind.MvcWebUi.Models.ProductListViewModel
@addTagHelper *,Abc2.Northwind.MvcWebUi


<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Product Name</th>
                <th scope="col">Unit Price</th>
                <th scope="col">Units in Stock</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in Model.Products)
            {
                <tr>
                    <td>@product.ProductName</td>
                    <td>@product.UnitPrice</td>
                    <td>@product.UnitsInStock</td>
                    <td><a class="btn btn-xs btn-info" asp-controller="Cart" asp-action="AddToCart" asp-route-productId="@product.ProductId">Add To Cart</a></td>
                </tr>
            }


        </tbody>
    </table>
</div>

<product-list-pager current-category-id="@Model.CurrentCategoryId" current-page="@Model.CurrentPage" page-count="@Model.PageCount" page-size="@Model.PageSize"></product-list-pager>